---
name: linting
on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: pylint
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "*.py"
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
      - name: pycodestyle
        uses: ricardochaves/python-lint@v1.3.0
        with:
          use-pylint: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
